// Independent offline acceptance: recorded controls only, no controller imports or calls.
import {readFileSync,readdirSync,mkdirSync,writeFileSync} from 'node:fs';
import {resolve,dirname,join} from 'node:path';import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';import {isDeepStrictEqual} from 'node:util';import {inflateRawSync,gunzipSync,gzipSync} from 'node:zlib';
import {verifyRaw,parse,serialize,sha256,sensorPacket,verifySources} from '../physics-replay.mjs';
import {createResolvedWorld,step,percept,hashWorld} from '../../repo/experimental/world.mjs';
import {createProofReducer,validateProofStructure} from '../../repo-final/experimental/proof-representation.mjs';
import {createBlockRawStream,verifyBlockRaw} from '../../repo-final/experimental/block-stream.mjs';
const out=dirname(fileURLToPath(import.meta.url)),root=resolve(out,'../..'),pilot=join(root,'pilot-attempt-002');
const eq=(a,b,l)=>{if(!isDeepStrictEqual(a,b))throw new Error(l+' mismatch: '+serialize(a).slice(0,400)+' vs '+serialize(b).slice(0,400));};
const manifest=JSON.parse(readFileSync(join(root,'PILOT002-FILE-MANIFEST.json'))),sourceManifest=JSON.parse(readFileSync(join(root,'COMPACT-SOURCE-MANIFEST.json')));
function preserved(){for(const f of manifest.files){const b=readFileSync(join(pilot,f.path));eq(b.length,f.bytes,'preserved size '+f.path);eq(sha256(b),f.sha256,'preserved hash '+f.path);}for(const f of sourceManifest.files)eq(sha256(readFileSync(join(root,'repo-compact',f.path))),f.sha256,'pilot002 source '+f.path);return {pilotFiles:manifest.files.length,pilotSourceFiles:sourceManifest.files.length};}
const independentFields={reportDigests:'actualReportSha256',comparedFieldDigests:'comparedFieldsSha256',perceptDigests:'perceptHashes'};
function seed(name,task){return createHash('sha256').update(serialize(['tether-proof-sequence-v1',name,task.id,task.seat])+'\n');}
function entry(h,r,value,present=true){h.update(serialize(['entry',r.decisionIndex,r.receiptTick,r.sensorTick,present,value])+'\n');}
function commitments(rows){const t=rows[0].task,ds=rows.filter(r=>r.type==='decision');return Object.fromEntries(Object.entries(independentFields).map(([name,key])=>{const h=seed(name,t);for(const d of ds)entry(h,d,d[key],Object.hasOwn(d,key));return [name,{count:ds.length,sha256:h.digest('hex')}];}));}
// Separate implementation of block validation, with gzip CRC/ISIZE validated by gunzip.
function independentBlocks(bytes,receipt){eq(bytes.length,receipt.bytes,'physical length');eq(sha256(bytes),receipt.fileSha256,'physical hash');let at=0,n=0,b=0,tail='0'.repeat(64),logical='',dataAll='',records=[],members=[];while(at<bytes.length){eq([...bytes.subarray(at,at+4)],[31,139,8,0],'gzip header');const inflated=inflateRawSync(bytes.subarray(at+10),{info:true});const end=at+10+inflated.engine.bytesWritten+8;eq(end<=bytes.length,true,'complete gzip member');const member=bytes.subarray(at,end),txt=gunzipSync(member).toString('utf8');eq(txt.endsWith('\n'),true,'newline');const lines=txt.slice(0,-1).split('\n'),p=JSON.parse(lines.pop());eq(Object.keys(p),['blockProof'],'proof envelope');const first=n,data=lines.join('\n')+'\n';eq(lines.length>0&&lines.length<=256,true,'block length');if(end<bytes.length)eq(lines.length,256,'nonfinal full block');eq(p.blockProof,{index:b,firstSequence:first,records:lines.length,previous:tail,digest:sha256(tail+'\n'+b+'\n'+first+'\n'+data)},'block proof');for(const line of lines){const x=parse(line);eq(Object.keys(x).sort(),['record','sequence'],'data envelope');eq(x.sequence,n++,'sequence');records.push(x.record);}tail=p.blockProof.digest;b++;logical+=txt;dataAll+=data;members.push(member);at=end;}eq({rows:n,blocks:b,chainTail:tail,uncompressedBytes:Buffer.byteLength(logical),sha256:sha256(logical),recordSequenceSha256:sha256(dataAll)},Object.fromEntries(['rows','blocks','chainTail','uncompressedBytes','sha256','recordSequenceSha256'].map(k=>[k,receipt[k]])),'receipt');return {records,members};}
function scientific(source,newRows){eq(newRows.length,source.length+1,'one technical row added');const proof=newRows.at(-2);eq(proof.type,'observer-proof-sequences','mandatory final proof');let defs=0,refs=0;const dictionary=new Map(),unique=new Set();for(let i=0;i<source.length;i++){const old=source[i],neo=newRows[i===source.length-1?i+1:i];const reconstructed=structuredClone(neo);if(i===0){eq(reconstructed.proofRepresentation,'ordered-task-and-block-v1','representation marker');delete reconstructed.proofRepresentation;}if(old.type==='decision'){for(const key of Object.values(independentFields)){eq(Object.hasOwn(neo,key),false,'omitted proof '+key);reconstructed[key]=old[key];}for(const d of reconstructed.definitions){eq(d.id,defs++,'dictionary sequential index');eq(Object.hasOwn(d,'contentHash'),false,'omitted content hash');const content=serialize([d.kind,d.value]);eq(unique.has(content),false,'unique complete definition');unique.add(content);dictionary.set(d.id,d);d.contentHash=sha256(content);}const co=neo.coordination;if(co)for(const id of [co.packet,...Object.values(co.deliveries??{}),co.forecastIssue,co.assessment,...['pending','lastAssessment','lastDisposition'].map(k=>co.monitor?.[k])])if(id!==null&&id!==undefined){eq(Number.isInteger(id)&&dictionary.has(id),true,'resolved backward dictionary ref');refs++;}}eq(reconstructed,old,'every scientific field/order row '+i);}eq(proof.sequences,commitments(source),'independent original digest sequences');eq(proof.dictionaryDefinitions,defs,'definition total');validateProofStructure(newRows);return {scientificRows:source.length,definitions:defs,dictionaryReferences:refs};}
const empty=()=>({moveX:0,moveY:0,aimX:0,aimY:0,throw:false,recall:false});
function replay(rows,original,result){const start=rows[0],task=start.task,w=createResolvedWorld(start.config),ds=rows.filter(r=>r.type==='decision'),ods=original.filter(r=>r.type==='decision'),events=original.filter(r=>r.type==='event'),cps=original.filter(r=>r.type==='world-checkpoint'),queue=[];let held=[empty(),empty()],di=0,ei=0,ci=0;const h=seed('perceptDigests',task);eq(hashWorld(w),start.initialHash,'initial hash');eq({players:w.players,spears:w.spears},start.initialTruth,'initial truth');for(let tick=0;tick<Math.round(task.seconds*120);tick++){eq(w.tick,tick,'tick');const views=['P1','P2'].map(id=>percept(w,id,task.mode));queue.push({sensorTime:w.elapsedSec,hashes:views.map(v=>sha256(sensorPacket(v))),visibility:views.map(v=>({opponent:!!v.opponent,opponentSpear:!!v.opponentSpear,ownSpear:!!v.own.spear}))});if(queue.length>19)queue.shift();let inputs=held.map(x=>({...x,throw:false,recall:false}));if(tick>=18&&(tick-18)%4===0){const d=ds[di];eq(d.receiptTick,tick,'receipt tick');eq(d.tick,tick,'decision tick');eq(d.decisionIndex,di,'decision index');eq(d.sensorTick,tick-18,'sensor tick');eq(d.simulatorReceiptTime,w.elapsedSec,'receipt time');eq(d.sensorTime,queue[0].sensorTime,'sensor time');eq(queue[0].hashes,ods[di].perceptHashes,'each reconstructed legal two-seat percept');eq(queue[0].visibility,d.visibility,'delayed visibility');entry(h,d,queue[0].hashes);inputs=structuredClone(d.inputs);eq(inputs.length,2,'two seats');held=inputs.map(x=>({...x,throw:false,recall:false}));di++;}for(const event of step(w,inputs))eq({type:'event',tick:w.tick,time:w.elapsedSec,event},events[ei++],'event exact timing/order');if(w.tick%120===0)eq({type:'world-checkpoint',tick:w.tick,time:w.elapsedSec,hash:hashWorld(w)},cps[ci++],'source checkpoint');}eq(di,ds.length,'all decisions');eq(ei,events.length,'all events');eq(ci,cps.length,'all checkpoints');eq(ci,30,'fixed120 checkpoints');const terminal={score:w.players.map(p=>p.score),elapsedSec:w.elapsedSec,finalHash:hashWorld(w)};for(const[k,v]of Object.entries(terminal)){eq(v,result[k],'external final '+k);eq(v,rows.at(-1).result[k],'raw final '+k);}eq(h.digest('hex'),rows.at(-2).sequences.perceptDigests.sha256,'reconstructed cumulative percept proof');return {ticks:w.tick,decisions:di,perceptHashes:di*2,events:ei,checkpoints:ci,terminal,controllerCalls:0,newGameplayDecisions:0};}
function mutations(bytes,receipt,rows){const tests=[];const reject=(label,fn)=>{let failed=false;try{fn();}catch{failed=true;}eq(failed,true,'mutation rejected '+label);tests.push(label);};let x=Buffer.from(bytes);x[15]^=1;reject('physical-corruption',()=>verifyBlockRaw(x,receipt));reject('truncation',()=>verifyBlockRaw(bytes.subarray(0,-1),receipt));const {members}=independentBlocks(bytes,receipt);x=Buffer.concat([members[1],members[0],...members.slice(2)]);reject('member-reorder-rehashed-physical',()=>verifyBlockRaw(x,{...receipt,fileSha256:sha256(x)}));x=Buffer.from(bytes);x[members[0].length-8]^=1;reject('bad-crc-rehashed-physical',()=>verifyBlockRaw(x,{...receipt,fileSha256:sha256(x)}));for(const [label,mut]of [['row-reorder',ls=>{[ls[0],ls[1]]=[ls[1],ls[0]];}],['row-delete',ls=>ls.splice(2,1)],['row-insert',ls=>ls.splice(2,0,ls[2])],['row-change',ls=>{const row=parse(ls[1]);row.record.mutation=true;ls[1]=serialize(row);} ]]){const ls=gunzipSync(members[0]).toString().trimEnd().split('\n');mut(ls);x=Buffer.concat([gzipSync(ls.join('\n')+'\n'),...members.slice(1)]);reject(label+'-rehashed-physical',()=>verifyBlockRaw(x,{...receipt,bytes:x.length,fileSha256:sha256(x)}));}reject('missing-final-observer-proof',()=>validateProofStructure(rows.filter(r=>r.type!=='observer-proof-sequences')));reject('misplaced-final-observer-proof',()=>validateProofStructure([rows.at(-2),...rows.filter(r=>r.type!=='observer-proof-sequences')]));return tests;}
const begun=new Date().toISOString(),t0=performance.now(),cpu0=process.cpuUsage();const preservedBefore=preserved(),frozenPhysics=verifySources();
const sourcePaths=['REPRESENTATION-AMENDMENT-PROOF-MAP.md','PILOT002-FILE-MANIFEST.json','COMPACT-SOURCE-MANIFEST.json','COMPACT-PILOT-LOCK.json','offline-validation/physics-replay.mjs','offline-validation/block-equivalence/acceptance.mjs','repo-final/experimental/proof-representation.mjs','repo-final/experimental/block-stream.mjs','repo-final/experimental/raw-stream.mjs'];const hashes=()=>sourcePaths.map(path=>({path,sha256:sha256(readFileSync(join(root,path)))})),sourcesBefore=hashes();
for(const dir of ['raw','receipts'])mkdirSync(join(out,dir),{recursive:true});const files=readdirSync(join(pilot,'results')).filter(f=>f.endsWith('.json')).sort();eq(files.length,192,'completed task inventory');const receipts=[];let mutationTests;
for(const f of files){const taskId=f.slice(0,-5),resultBytes=readFileSync(join(pilot,'results',f)),result=parse(resultBytes.toString()),oldBytes=readFileSync(join(pilot,'raw',taskId+'.jsonl.gz')),original=verifyRaw(oldBytes,result.raw),reducer=createProofReducer(),stream=createBlockRawStream(join(out,'raw',taskId+'.jsonl.gz'));try{for(const r of original.records)for(const x of reducer.reduce(r))stream.append(x);reducer.assertComplete();const raw=stream.finish(),bytes=readFileSync(join(out,'raw',taskId+'.jsonl.gz')),newRows=verifyBlockRaw(bytes,raw).records;eq(independentBlocks(bytes,raw).records,newRows,'independent block records');const counts=scientific(original.records,newRows),physics=replay(newRows,original.records,result);if(!mutationTests)mutationTests=mutations(bytes,raw,newRows);const receipt={taskId,status:'PASS',sourceRaw:original.integrity,sourceResultSha256:sha256(resultBytes),amendedRaw:raw,counts,physics,commitments:newRows.at(-2)};writeFileSync(join(out,'receipts',f),JSON.stringify(receipt,null,2)+'\n',{flag:'wx'});receipts.push(receipt);console.log(`${receipts.length}/192 PASS ${taskId}`);}catch(e){stream.abort();throw e;}}
const preservedAfter=preserved();eq(hashes(),sourcesBefore,'sources immutable during verification');eq(verifySources(),frozenPhysics,'frozen physics unchanged');const totals={};for(const k of ['ticks','decisions','perceptHashes','events','checkpoints'])totals[k]=receipts.reduce((s,r)=>s+r.physics[k],0);for(const k of ['scientificRows','definitions','dictionaryReferences'])totals[k]=receipts.reduce((s,r)=>s+r.counts[k],0);totals.originalBytes=receipts.reduce((s,r)=>s+r.sourceRaw.physicalBytes,0);totals.amendedBytes=receipts.reduce((s,r)=>s+r.amendedRaw.bytes,0);const cpu=process.cpuUsage(cpu0);const report={status:'PASS',sourceManifestNote:'Actual pilot002 source repo-compact verified against COMPACT-SOURCE-MANIFEST; saved pilot002 raw/results validated against immutable PILOT002-FILE-MANIFEST. Frozen physics verified against original PILOT-SOURCE-MANIFEST. Unexecuted repo-pilot002 reference is outside acceptance scope.',scope:'All192 saved pilot002 tasks; offline representation conversion and frozen recorded-control replay only. No controllers, new bouts, selection, training, or evaluation release.',metadataLoss:'Individual actual-report and native-compared-field proof digests cannot be reconstructed from sequence commitments. Every scientific field is exact; definition hashes reconstruct exactly; every legal percept digest is independently reconstructed. No claim of lossless retention of all proof bytes.',begun,completed:new Date().toISOString(),tasks:receipts.length,totals,mutationTests,preservedBefore,preservedAfter,sources:sourcesBefore,frozenPhysics,controllerCalls:0,newGameplayDecisions:0,wallMs:performance.now()-t0,cpuUserUs:cpu.user,cpuSystemUs:cpu.system,prospectiveCeiling:'36 CPU-hours applies only to separately released later evaluation; this receipt confers no runtime-pilot or full-evaluation release.'};writeFileSync(join(out,'REPORT.json'),JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(report,null,2));
