import {readFileSync,readdirSync,writeFileSync} from 'node:fs';import {dirname,join,resolve} from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
import {verifyBlockRaw} from '../../repo-final/experimental/block-stream.mjs';import {validateProofStructure} from '../../repo-final/experimental/proof-representation.mjs';import {verifyRaw,serialize,parse,sha256} from '../physics-replay.mjs';
const out=dirname(fileURLToPath(import.meta.url)),root=resolve(out,'../..'),results=[];const rejects=(name,fn)=>{assert.throws(fn);results.push({name,status:'REJECTED'});};
const f=readdirSync(join(out,'receipts')).sort().find(f=>f.includes('mind-full'));assert(f);const receipt=JSON.parse(readFileSync(join(out,'receipts',f))),bytes=readFileSync(join(out,'raw',f.replace('.json','.jsonl.gz'))),rows=verifyBlockRaw(bytes,receipt.amendedRaw).records;
for(const field of ['fileSha256','sha256','recordSequenceSha256','chainTail','rows','blocks','bytes','uncompressedBytes','format']){const r=structuredClone(receipt.amendedRaw);r[field]=typeof r[field]==='number'?r[field]+1:'incorrect';rejects('receipt-'+field,()=>verifyBlockRaw(bytes,r));}
for(const [name,change] of [['proof-seat',r=>r.at(-2).seat=1-r.at(-2).seat],['proof-task',r=>r.at(-2).taskId='another-task'],['proof-count',r=>r.at(-2).decisions++],['proof-sequence-count',r=>r.at(-2).sequences.perceptDigests.count++],['definition-alias',r=>{const d=r.flatMap(x=>x.definitions??[]);d[1].id=d[0].id;}],['forward-reference',r=>{r.find(x=>x.coordination).coordination.packet=999999;}],['duplicate-definition-content',r=>{const d=r.flatMap(x=>x.definitions??[]);d[1].kind=d[0].kind;d[1].value=structuredClone(d[0].value);}],['decision-order',r=>{const ds=r.filter(x=>x.type==='decision');ds[0].decisionIndex=1;}],['retained-redundant-proof',r=>r.find(x=>x.type==='decision').actualReportSha256=null]]){const r=structuredClone(rows);change(r);rejects(name,()=>validateProofStructure(r));}
const origResult=parse(readFileSync(join(root,'pilot-attempt-002/results',f),'utf8')),orig=verifyRaw(readFileSync(join(root,'pilot-attempt-002/raw',f.replace('.json','.jsonl.gz'))),origResult.raw).records,ds=orig.filter(r=>r.type==='decision'),task=orig[0].task;
const seq=(name,records,taskArg=task,presence=true)=>{const h=createHash('sha256').update(serialize(['tether-proof-sequence-v1',name,taskArg.id,taskArg.seat])+'\n');for(const r of records)h.update(serialize(['entry',r.decisionIndex,r.receiptTick,r.sensorTick,presence,r.actualReportSha256])+'\n');return h.digest('hex');};const expected=seq('reportDigests',ds);assert.equal(expected,rows.at(-2).sequences.reportDigests.sha256);
for(const [name,value]of [['entry-order',seq('reportDigests',[...ds].reverse())],['task-identity',seq('reportDigests',ds,{...task,id:task.id+'x'})],['seat-identity',seq('reportDigests',ds,{...task,seat:1-task.seat})],['presence-marker',seq('reportDigests',ds,task,false)],['sequence-name',seq('comparedFieldDigests',ds)],['entry-deletion',seq('reportDigests',ds.slice(1))],['entry-insertion',seq('reportDigests',[ds[0],...ds])]]){assert.notEqual(value,expected);results.push({name:'commitment-'+name,status:'DIFFERENT'});}
const report={status:'PASS',fixture:receipt.taskId,tests:results.length,results,verifierSha256:sha256(readFileSync(fileURLToPath(import.meta.url))),scope:'Offline corruption, framing, definition alias/reference and independently constructed commitment identity/order/presence negative tests. No controllers or new bouts.'};writeFileSync(join(out,'NEGATIVE-TESTS.json'),JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(report,null,2));
