import {openSync,writeSync,fsyncSync,closeSync,chmodSync} from 'node:fs';import {createHash} from 'node:crypto';import {gzipSync,gunzipSync,inflateRawSync} from 'node:zlib';import {serialize,parse,sha256} from './raw-stream.mjs';
export function createBlockRawStream(path,{maxBytes=Infinity}={}){
 const fd=openSync(path,'wx'),physical=createHash('sha256'),logical=createHash('sha256'),recordHash=createHash('sha256');let sequence=0,blocks=0,bytes=0,uncompressedBytes=0,persistedRows=0,previous='0'.repeat(64),pending=[],closed=false;
 const flush=()=>{if(!pending.length)return;const data=pending.join(''),firstSequence=sequence-pending.length,digest=sha256(`${previous}\n${blocks}\n${firstSequence}\n${data}`),proof={blockProof:{index:blocks,firstSequence,records:pending.length,previous,digest}},text=data+serialize(proof)+'\n',buffer=gzipSync(Buffer.from(text),{level:6});if(bytes+buffer.length>maxBytes)throw new Error('raw stream byte ceiling exceeded');let offset=0;while(offset<buffer.length){const n=writeSync(fd,buffer,offset,buffer.length-offset);if(n<=0)throw new Error('raw stream write made no progress');offset+=n;}physical.update(buffer);logical.update(text);recordHash.update(data);bytes+=buffer.length;uncompressedBytes+=Buffer.byteLength(text);persistedRows+=pending.length;pending=[];previous=digest;blocks++;};
 return {append(record){if(closed)throw new Error('stream closed');pending.push(serialize({sequence,record})+'\n');sequence++;if(pending.length===256)flush();},finish(){if(closed)throw new Error('stream closed');flush();fsyncSync(fd);closeSync(fd);chmodSync(path,0o444);closed=true;return {format:'JSONL-BLOCK-v2',compression:'gzip-members-256-records',rows:sequence,blocks,bytes,uncompressedBytes,chainTail:previous,sha256:logical.digest('hex'),recordSequenceSha256:recordHash.digest('hex'),fileSha256:physical.digest('hex')};},abort(){if(!closed){try{flush();}catch{}fsyncSync(fd);closeSync(fd);chmodSync(path,0o444);closed=true;return {format:'JSONL-BLOCK-v2',persistedRows,persistedBytes:bytes,bufferedRowsNotPersisted:pending.length};}}};
}
export function verifyBlockRaw(bytes,receipt){
 const equal=(a,b,label)=>{if(a!==b)throw new Error(`block stream ${label}`);};equal(receipt.format,'JSONL-BLOCK-v2','format');equal(bytes.length,receipt.bytes,'physical bytes');equal(sha256(bytes),receipt.fileSha256,'physical hash');
 let offset=0,sequence=0,blocks=0,previous='0'.repeat(64),uncompressedBytes=0,shortBlock=false;const logical=createHash('sha256'),recordHash=createHash('sha256'),records=[];
 while(offset<bytes.length){if(shortBlock)throw new Error('record after partial final block');if(bytes.length-offset<18||bytes[offset]!==31||bytes[offset+1]!==139||bytes[offset+2]!==8||bytes[offset+3]!==0)throw new Error('unsupported/truncated gzip member');
  const inflated=inflateRawSync(bytes.subarray(offset+10),{info:true}),end=offset+10+inflated.engine.bytesWritten+8;if(end>bytes.length)throw new Error('truncated gzip footer');const text=gunzipSync(bytes.subarray(offset,end)).toString('utf8');equal(text,inflated.buffer.toString('utf8'),'gzip member identity');if(!text.endsWith('\n'))throw new Error('unclosed JSONL member');const lines=text.slice(0,-1).split('\n');if(lines.length<2||lines.length>257)throw new Error('invalid block row count');
  const proofEnvelope=JSON.parse(lines.at(-1));if(Object.keys(proofEnvelope).join()!=='blockProof')throw new Error('missing member proof');const p=proofEnvelope.blockProof,dataLines=lines.slice(0,-1),data=dataLines.join('\n')+'\n';equal(p.index,blocks,'index');equal(p.firstSequence,sequence,'first sequence');equal(p.records,dataLines.length,'block count');equal(p.previous,previous,'previous block');equal(p.digest,sha256(`${previous}\n${blocks}\n${sequence}\n${data}`),'block hash');
  for(const line of dataLines){const envelope=parse(line);if(Object.keys(envelope).sort().join()!=='record,sequence'||envelope.sequence!==sequence)throw new Error('invalid/unproved/reordered record');records.push(envelope.record);sequence++;}
  logical.update(text);recordHash.update(data);uncompressedBytes+=Buffer.byteLength(text);previous=p.digest;blocks++;shortBlock=dataLines.length<256;offset=end;
 }
 equal(sequence,receipt.rows,'total rows');equal(blocks,receipt.blocks,'total blocks');equal(previous,receipt.chainTail,'chain tail');equal(uncompressedBytes,receipt.uncompressedBytes,'logical bytes');equal(logical.digest('hex'),receipt.sha256,'logical hash');equal(recordHash.digest('hex'),receipt.recordSequenceSha256,'record sequence hash');return {records,rows:sequence,blocks};
}
