import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {execute,cancelActive,active,resourceTotals} from './execution.mjs';
test('mock child timeout terminates and rejects without game imports',async()=>{const root=await mkdtemp(join(tmpdir(),'tether-timeout-'));try{const workerPath=join(root,'mock.cjs');await writeFile(workerPath,"process.once('message',()=>setInterval(()=>{},1000));");await assert.rejects(execute({limits:{maxTaskWallSeconds:.05},rawPath:join(root,'raw')},{workerPath}),/task wall ceiling/);assert.equal(active.size,0);}finally{await rm(root,{recursive:true,force:true});}});
test('explicit cancellation terminates active mock child',async()=>{const root=await mkdtemp(join(tmpdir(),'tether-cancel-'));try{const workerPath=join(root,'mock.cjs');await writeFile(workerPath,"process.once('message',()=>setInterval(()=>{},1000));");const promise=execute({limits:{maxTaskWallSeconds:10},rawPath:join(root,'raw')},{workerPath});setTimeout(cancelActive,30);await assert.rejects(promise,/worker exit/);assert.equal(active.size,0);}finally{await rm(root,{recursive:true,force:true});}});
test('disjoint completed/live totals include parent CPU and raw ceilings',()=>{const sample={completedCpuSeconds:10,liveCpuSeconds:3,parentUsage:{userCPUTime:1500000,systemCPUTime:500000},completedRawBytes:20,liveRawBytes:5};assert.deepEqual(resourceTotals(sample,{maxPhaseCpuSeconds:15,maxPhaseRawBytes:25}),{cpuSeconds:15,rawBytes:25});assert.throws(()=>resourceTotals(sample,{maxPhaseCpuSeconds:14,maxPhaseRawBytes:25}));assert.throws(()=>resourceTotals(sample,{maxPhaseCpuSeconds:15,maxPhaseRawBytes:24}));assert.throws(()=>resourceTotals({...sample,liveCpuSeconds:0,completedCpuSeconds:14},{maxPhaseCpuSeconds:15,maxPhaseRawBytes:25}));});
test('procfs exit races alone are tolerated',async()=>{
 const {readLiveProcess}=await import('./execution.mjs');for(const code of ['ESRCH','ENOENT']){const seen=[];const result=await readLiveProcess(123,async path=>{seen.push(path);throw Object.assign(new Error('gone'),{code});});assert.deepEqual(result,{exited:true,reason:code});assert.deepEqual(seen,['/proc/123/stat']);}
 await assert.rejects(readLiveProcess(123,async()=>{throw Object.assign(new Error('denied'),{code:'EACCES'});}),/denied/);
 await assert.rejects(readLiveProcess(123,async()=> 'malformed'),/invalid live process/);
});
test('accounting tolerates only explicit terminal/zombie states and raced status exit',async()=>{
 const {readLiveProcess}=await import('./execution.mjs');const stat='123 (mock) S '+Array(30).fill('0').join(' ');
 assert.deepEqual(await readLiveProcess(123,async path=>{if(path.endsWith('/stat'))return stat;throw Object.assign(new Error('gone'),{code:'ESRCH'});}),{exited:true,reason:'ESRCH'});
 for(const state of ['Z','X','x'])assert.deepEqual(await readLiveProcess(123,async path=>path.endsWith('/stat')?stat:`Name:\tmock\nState:\t${state} (terminal)\n`),{exited:true,reason:`process-state-${state}`});
 await assert.rejects(readLiveProcess(123,async path=>path.endsWith('/stat')?stat:'Name:\tmock\nState:\tR (running)\n'),/invalid live process/);
 assert.deepEqual(await readLiveProcess(123,async path=>path.endsWith('/stat')?stat:'Name:\tmock\nState:\tR (running)\nVmRSS:\t123 kB\n'),{exited:false,userTicks:0,systemTicks:0,rssBytes:123*1024});
});
