import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile,writeFile,mkdir,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createRawStream,verifyRawText,sha256,serialize,parse} from './raw-stream.mjs';import {consumeRelease,buildLock,verifyLock} from './lock.mjs';
import {createResolvedWorld} from './world.mjs';import {CONSTANTS,createWorld} from '../src/sim.js';
test('raw stream is exclusive, independently verifiable and detects tampering',async()=>{const root=await mkdtemp(join(tmpdir(),'tether-stream-'));try{const path=join(root,'raw.jsonl'),s=createRawStream(path);s.append({type:'synthetic',value:1});s.append({type:'synthetic',value:2});const receipt=s.finish(),text=await readFile(path,'utf8');assert.deepEqual(verifyRawText(text),receipt);assert.throws(()=>verifyRawText(text.replace('"value":1','"value":9')));assert.throws(()=>createRawStream(path));assert.throws(()=>s.append({}));}finally{await rm(root,{recursive:true,force:true});}});
test('resolved config validates nominal fields and default byte parity',()=>{const config={id:'default',experiment:structuredClone(CONSTANTS.experiment),technical:CONSTANTS.technical,publicControllerRules:{outboundSpeed:12,returnSpeed:12}};assert.deepEqual(createResolvedWorld(config),createWorld());config.experiment.PLAYER_SPEED=5;assert.throws(()=>createResolvedWorld(config));});
test('release needs exact review, checkpoint, root phase and is consumed only once',async()=>{
 const root=await mkdtemp(join(tmpdir(),'tether-guard-'));try{
  for(const d of ['src','benchmark','experimental','prereg','freeze'])await mkdir(join(root,d));await writeFile(join(root,'src','x.js'),'frozen');await writeFile(join(root,'package.json'),'{}');
  const lock=await buildLock({repo:root,prereg:join(root,'prereg'),freeze:join(root,'freeze'),phase:'pilot'}),lockPath=join(root,'lock.json');await writeFile(lockPath,JSON.stringify(lock));const lockSha256=sha256(await readFile(lockPath));
  const reviewPath=join(root,'review.json'),checkpointPath=join(root,'checkpoint.json');await writeFile(reviewPath,JSON.stringify({approved:true,lockSha256}));await writeFile(checkpointPath,JSON.stringify({status:'VERIFIED',lockSha256}));
  const release={authorized:true,phase:'pilot',lockSha256,output:join(root,'out'),workers:1,independentReview:{path:reviewPath,sha256:sha256(await readFile(reviewPath))},gitCheckpoint:{path:checkpointPath,sha256:sha256(await readFile(checkpointPath))}},releasePath=join(root,'release.json');await writeFile(releasePath,JSON.stringify(release));
  await assert.rejects(consumeRelease(releasePath,lockPath,'evaluation',release.output,1));await assert.rejects(consumeRelease(releasePath,lockPath,'pilot',release.output,2));
  await consumeRelease(releasePath,lockPath,'pilot',release.output,1);await assert.rejects(consumeRelease(releasePath,lockPath,'pilot',release.output,1));
  await writeFile(join(root,'src','new.js'),'unlocked');await assert.rejects(verifyLock(lock));
 }finally{await rm(root,{recursive:true,force:true});}
});

test('nonfinite native fields survive tagged serialization',()=>{const value={a:Infinity,b:-Infinity,c:NaN,nested:[1,Infinity]};const recovered=parse(serialize(value));assert.deepEqual(recovered,value);});
test('closure handles opponent freeze already within locked directory',async()=>{const root=await mkdtemp(join(tmpdir(),'tether-overlap-'));try{for(const d of ['src','benchmark','experimental','prereg','freeze'])await mkdir(join(root,d));await writeFile(join(root,'package.json'),'{}');const opponentFreeze=join(root,'prereg','opponent.json');await writeFile(opponentFreeze,'{}');const lock=await buildLock({repo:root,prereg:join(root,'prereg'),freeze:join(root,'freeze'),phase:'evaluation',opponentFreeze});await verifyLock(lock);await writeFile(join(root,'freeze','unlocked.json'),'{}');await assert.rejects(verifyLock(lock));}finally{await rm(root,{recursive:true,force:true});}});
test('exact pilot grid rejects substituted, missing, and duplicate logical cells',async()=>{
 const {validateTaskGrid}=await import('./plan-validation.mjs');const design={arms:Array.from({length:8},(_,i)=>({id:`arm${i}`})),roster:['a','b','c','d']};
 const tasks=[['dev-a',0],['dev-b',5],['dev-c',10]].flatMap(([cluster,snapshotIndex])=>['default','arena-mirror-x'].flatMap(condition=>design.arms.flatMap(({id:arm})=>[0,1].flatMap(seat=>[0,1].map(bout=>({cluster,snapshotIndex,condition,arm,seat,bout,controlOpponent:design.roster[snapshotIndex%4]}))))));
 validateTaskGrid(design,tasks,'pilot');assert.throws(()=>validateTaskGrid(design,tasks.slice(1),'pilot'));
 const duplicate=structuredClone(tasks);duplicate[0]={...duplicate[1]};assert.throws(()=>validateTaskGrid(design,duplicate,'pilot'));
 const mapped=structuredClone(tasks);mapped[0].snapshotIndex=1;assert.throws(()=>validateTaskGrid(design,mapped,'pilot'));
});
test('raw byte ceiling preserves partial stream and forbids success',async()=>{const root=await mkdtemp(join(tmpdir(),'tether-byte-cap-'));try{const path=join(root,'raw.jsonl'),s=createRawStream(path,{maxBytes:512});s.append({type:'synthetic',value:1});assert.throws(()=>s.append({type:'synthetic',value:'x'.repeat(1000)}));s.abort();const text=await readFile(path,'utf8');assert.equal(verifyRawText(text).rows,1);assert.throws(()=>s.finish());}finally{await rm(root,{recursive:true,force:true});}});
test('compressed member streams preserve every row and physical digest',async()=>{const {gunzipSync}=await import('node:zlib');const root=await mkdtemp(join(tmpdir(),'tether-gzip-'));try{const path=join(root,'raw.gz'),s=createRawStream(path,{gzip:true,maxBytes:1000000});for(let i=0;i<600;i++)s.append({type:'synthetic',i,value:Infinity});const receipt=s.finish(),bytes=await readFile(path),text=gunzipSync(bytes).toString();assert.equal(receipt.fileSha256,sha256(bytes));assert.equal(receipt.bytes,bytes.length);assert.equal(receipt.uncompressedBytes,Buffer.byteLength(text));assert.equal(verifyRawText(text).sha256,receipt.sha256);assert.equal(verifyRawText(text).rows,600);}finally{await rm(root,{recursive:true,force:true});}});
