// Pure search arithmetic and task planning. Never imports a game runner.
import {sha256} from './raw-stream.mjs';
export const BASELINE='36398123d89881576443145b0b7826c8cf2203c9';
export function vector(v){if(!Array.isArray(v)||v.length!==21||v.some(x=>!Number.isFinite(x)||x<0||x>1))throw Error('invalid normalized 21D vector');return v;}
export function mutate(parent,seed){vector(parent);if(!Number.isInteger(seed)||seed<1||seed>0xffffffff)throw Error('invalid mutation seed');let state=seed>>>0;const u=()=>{state^=state<<13;state^=state>>>17;state^=state<<5;return (state>>>0)/4294967296;};return parent.map(x=>Math.max(0,Math.min(1,x+.16*(u()+u()+u()+u()-2))));}
export function compare(a,b){if(!Number.isSafeInteger(a.totalNet)||!Number.isSafeInteger(b.totalNet))throw Error('integer ranking required');if(a.totalNet!==b.totalNet)return a.totalNet>b.totalNet?-1:1;for(let k=0;k<21;k++){if(a.vector[k]!==b.vector[k])return a.vector[k]<b.vector[k]?-1:1;}return a.id<b.id?-1:a.id>b.id?1:0;}
export function generation(design,initial,g,previous=[]){if(!Number.isInteger(g)||g<0||g>7||initial.length!==5)throw Error('invalid generation');if(g&&previous.length!==16)throw Error('complete preceding generation required');const parents=g?[...previous].sort(compare).slice(0,4):initial;return Array.from({length:16},(_,i)=>{const seed=design.searchSeeds[g].mutationSeeds[i],unchanged=g===0&&i<5,parent=parents[g?i%4:unchanged?i:(i-5)%5],v=unchanged?[...vector(parent.vector)]:mutate(parent.vector,seed);return {id:`search-g${g}-c${String(i).padStart(2,'0')}`,generation:g,index:i,kind:'param',mutated:!unchanged,parentId:parent.id??parent.name,mutationSeed:unchanged?null:seed,vector:v,parameterSha256:sha256(v)};});}
export function tasksFor(design,candidate,snapshotSha256){return design.searchSeeds[candidate.generation].tasks.map((seed,i)=>({id:`${candidate.id}-t${i}`,phase:'opponent-search',mode:'MODE_B',condition:'default',seconds:300,candidateId:candidate.id,candidateSeat:seed.seat,targetSeat:1-seed.seat,candidateSeed:seed.controllerSeed,targetSeed:seed.targetSeed,seat:1-seed.seat,arm:seed.target,target:seed.target,controllerSeed:seed.targetSeed,opponentSeed:seed.controllerSeed,episodeSeed:seed.episodeSeed,snapshotIndex:0,initialMemory:seed.target==='mind-full'?'snapshots/mind-0.json':null,snapshotSha256:seed.target==='mind-full'?snapshotSha256:null,configSha256:design.configHashes.default,opponent:candidate.id,parameterSha256:candidate.parameterSha256}));}
export function reduceCandidate(candidate,tasks,results){if(tasks.length!==4||results.length!==4||new Set(results.map(r=>r.taskId)).size!==4)throw Error('exact four unique task results required');let totalNet=0;for(const task of tasks){const r=results.find(r=>r.taskId===task.id);if(!r||r.score?.length!==2||r.score.some(x=>!Number.isSafeInteger(x)||x<0))throw Error('missing result or noninteger score');const n=r.score[task.candidateSeat]-r.score[1-task.candidateSeat];totalNet+=n;if(!Number.isSafeInteger(totalNet))throw Error('integer score overflow');}return {...candidate,totalNet,taskIds:tasks.map(t=>t.id)};}
export function distanceSquared(a,b){vector(a);vector(b);let sum=0;for(let i=0;i<21;i++)sum+=(a[i]-b[i])**2;return sum/21;}
export function select(candidates,initial,design){if(candidates.length!==128||new Set(candidates.map(c=>c.id)).size!==128)throw Error('fixed 128-candidate budget required');const references=[...initial,...design.arms.filter(a=>['conventional','conventional-useful-2x','conventional-useful-4x'].includes(a.id))];if(references.length!==8)throw Error('eight frozen references required');return [...candidates].sort(compare).find(c=>c.mutated&&references.every(r=>distanceSquared(c.vector,r.vector)>=.01))??null;}
