// Read-only saved-record validation. Never imports a controller or executes a bout.
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {pathToFileURL} from 'node:url';
const [rootArg,logArg,lockArg,expectedLock,planArg,phase,offsetArg,countArg,outArg]=process.argv.slice(2),root=path.resolve(rootArg),out=path.resolve(outArg),offset=Number(offsetArg),count=Number(countArg);if(!Number.isInteger(offset)||offset<0||!Number.isInteger(count)||count<1||count>64)throw Error('invalid bounded batch');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),lockBytes=fs.readFileSync(lockArg);if(sha(lockBytes)!==expectedLock)throw Error('lock hash');const lock=JSON.parse(lockBytes);for(const i of lock.inputs)if(sha(fs.readFileSync(i.path))!==i.sha256)throw Error('source/input drift '+i.path);
if(!lock.inputs.some(i=>path.resolve(i.path)===path.resolve(planArg)))throw Error('plan outside closed inputs');
const {parse,serialize}=await import(pathToFileURL(path.join(lock.repo,'experimental/raw-stream.mjs'))),{verifyBlockRaw}=await import(pathToFileURL(path.join(lock.repo,'experimental/block-stream.mjs'))),{validateProofStructure}=await import(pathToFileURL(path.join(lock.repo,'experimental/proof-representation.mjs')));
const {verifyLock}=await import(pathToFileURL(path.join(lock.repo,'experimental/lock.mjs')));await verifyLock(lock);const release=JSON.parse(fs.readFileSync(path.join(root,'RELEASE.json')));if(release.authorized!==true||release.phase!==phase||lock.phase!==phase||release.lockSha256!==expectedLock||path.resolve(release.output)!==root)throw Error('release/run mismatch');
const plan=JSON.parse(fs.readFileSync(planArg)),tasks=new Map(plan.map(t=>[t.id,t]));if(tasks.size!==plan.length)throw Error('duplicate plan IDs');const log=fs.readFileSync(logArg,'utf8'),lines=log.split('\n').slice(0,-1),accepted=[],seen=new Set();
for(const line of lines){let p;try{p=JSON.parse(line);}catch{continue;}if(p.type!=='progress'||p.phase!==phase)continue;if(seen.has(p.taskId)||!tasks.has(p.taskId)||p.completed!==accepted.length+1||p.total!==plan.length)throw Error('invalid progress identity/order');seen.add(p.taskId);accepted.push({line,progress:p});}
const selected=accepted.slice(offset,offset+count);if(selected.length!==count)throw Error('batch incomplete');if(fs.existsSync(out))throw Error('output exists');fs.mkdirSync(out,{recursive:true});const files=[],ids=[];
function member(rel){const p=path.join(root,rel),s=fs.lstatSync(p);if(!s.isFile()||s.isSymbolicLink())throw Error('unsafe input');const b=fs.readFileSync(p);files.push({source:p,member:rel,bytes:b.length,sha256:sha(b)});return b;}
for(const {progress:p}of selected){const id=p.taskId;if(!/^[a-zA-Z0-9_-]+$/.test(id))throw Error('unsafe ID');const r=parse(member('results/'+id+'.json'));if(r.taskId!==id)throw Error('result identity');const raw=member('raw/'+id+'.jsonl.gz'),v=verifyBlockRaw(raw,r.raw);validateProofStructure(v.records);if(serialize(v.records[0].task)!==serialize(tasks.get(id)))throw Error('assignment mismatch');if(v.records[0].provenance?.lockSha256!==expectedLock)throw Error('task provenance lock');const terminal=v.records.at(-1).result;const {raw:rawReceipt,...saved}=r;const {processLifetimeCpu,...savedResources}=saved.resources;saved.resources=savedResources;if(serialize(terminal)!==serialize(saved))throw Error('terminal result mismatch');if(r.outputMemorySha256){const b=member('memory/'+id+'.json');if(sha(serialize(parse(b)))!==r.outputMemorySha256)throw Error('memory mismatch');}ids.push(id);}
const progressPath=path.join(out,'ACCEPTED-PROGRESS.jsonl'),progressBytes=selected.map(x=>x.line).join('\n')+'\n';fs.writeFileSync(progressPath,progressBytes,{flag:'wx'});files.push({source:progressPath,member:'ACCEPTED-PROGRESS.jsonl',bytes:Buffer.byteLength(progressBytes),sha256:sha(progressBytes)});
for(const rel of ['LOCK.json','RELEASE.json']){const b=fs.readFileSync(path.join(root,rel));if(rel==='LOCK.json'&&sha(b)!==expectedLock)throw Error('attempt lock');}
const m={format:1,status:'IMMUTABLE_COMPLETED_TASK_BATCH',archiveName:`${phase}-${offset+1}-${offset+count}.tar.gz`,phase,lockSha256:expectedLock,releaseSha256:sha(fs.readFileSync(path.join(root,'RELEASE.json'))),sourceInputManifestSha256:sha(JSON.stringify(lock.inputs)),completedProgressRange:[offset+1,offset+count],taskIds:ids,taskCount:count,wholePhaseCpuClaim:false,files};fs.writeFileSync(path.join(out,'LOCAL-MEMBERS.json'),JSON.stringify(m,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({taskCount:count,files:files.length,manifest:path.join(out,'LOCAL-MEMBERS.json')}));
