// Read-only completed-generation archival selector; no candidate or controller execution.
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {pathToFileURL} from 'node:url';
const [rootArg,lockArg,expectedLock,gArg,outArg]=process.argv.slice(2),root=path.resolve(rootArg),out=path.resolve(outArg),g=Number(gArg),sha=b=>crypto.createHash('sha256').update(b).digest('hex');if(!Number.isInteger(g)||g<0||g>7)throw Error('generation');
const lockBytes=fs.readFileSync(lockArg);if(sha(lockBytes)!==expectedLock)throw Error('lock identity');const lock=JSON.parse(lockBytes);for(const f of lock.inputs)if(sha(fs.readFileSync(f.path))!==f.sha256)throw Error('source drift');
const {verifyLock}=await import(pathToFileURL(path.join(lock.repo,'experimental/lock.mjs'))),{parse,serialize}=await import(pathToFileURL(path.join(lock.repo,'experimental/raw-stream.mjs'))),{verifyBlockRaw}=await import(pathToFileURL(path.join(lock.repo,'experimental/block-stream.mjs'))),{validateProofStructure}=await import(pathToFileURL(path.join(lock.repo,'experimental/proof-representation.mjs')));await verifyLock(lock);
const releaseBytes=fs.readFileSync(path.join(root,'RELEASE.json')),release=JSON.parse(releaseBytes);if(release.authorized!==true||release.phase!=='opponent-search'||lock.phase!=='opponent-search'||release.lockSha256!==expectedLock||path.resolve(release.output)!==root||sha(fs.readFileSync(path.join(root,'LOCK.json')))!==expectedLock)throw Error('release/run identity');
const files=[];function member(rel){const p=path.join(root,rel),s=fs.lstatSync(p);if(!s.isFile()||s.isSymbolicLink())throw Error('unsafe input');const b=fs.readFileSync(p);files.push({source:p,member:rel,bytes:b.length,sha256:sha(b)});return b;}
const p=parse(member(`generations/g${g}-plan.json`)),accepted=parse(member(`generations/g${g}-results.json`));if(p.generation!==g||p.lockSha256!==expectedLock||p.tasks.length!==64||accepted.results.length!==64||p.candidates.length!==16||accepted.candidates.length!==16)throw Error('incomplete generation');const tasks=new Map(p.tasks.map(t=>[t.id,t]));if(tasks.size!==64||new Set(accepted.results.map(r=>r.taskId)).size!==64)throw Error('duplicate IDs');const taskIds=[];
for(const a of accepted.results){const id=a.taskId,t=tasks.get(id);if(!t||!/^[a-zA-Z0-9_-]+$/.test(id)||t.phase!=='opponent-search')throw Error('task identity');const r=parse(member('results/'+id+'.json')),{terminalResourceUsage,...acceptedDisk}=a;if(!terminalResourceUsage||serialize(acceptedDisk)!==serialize(r))throw Error('parent acceptance mismatch');const v=verifyBlockRaw(member('raw/'+id+'.jsonl.gz'),r.raw);validateProofStructure(v.records);const start=v.records[0];if(serialize(start.task)!==serialize(t)||start.provenance?.lockSha256!==expectedLock||start.provenance?.generationManifestSha256!==sha(serialize(p)))throw Error('task provenance');const {raw,candidateSeat,candidateIntegerNet,...terminal}=r;if(serialize(v.records.at(-1).result)!==serialize(terminal))throw Error('terminal mismatch');if(candidateSeat!==t.candidateSeat||candidateIntegerNet!==r.score[candidateSeat]-r.score[1-candidateSeat])throw Error('candidate integer result');if(fs.existsSync(path.join(root,'memory',id+'.json')))throw Error('unexpected persisted target memory');taskIds.push(id);}
// Recheck every source, including the parent completion marker, before freezing this archival list.
for(const f of files){const b=fs.readFileSync(f.source);if(b.length!==f.bytes||sha(b)!==f.sha256)throw Error('input changed during validation');}
const m={format:1,status:'IMMUTABLE_COMPLETED_SEARCH_GENERATION',archiveName:`opponent-search-g${g}.tar.gz`,phase:'opponent-search',generation:g,lockSha256:expectedLock,releaseSha256:sha(releaseBytes),sourceInputManifestSha256:sha(JSON.stringify(lock.inputs)),taskIds,taskCount:64,parentCompletionMarker:`generations/g${g}-results.json`,wholePhaseCpuClaim:false,noTargetMemoryPersisted:true,files};if(fs.existsSync(out))throw Error('output exists');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'LOCAL-MEMBERS.json'),JSON.stringify(m,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({generation:g,tasks:64,files:files.length,manifest:path.join(out,'LOCAL-MEMBERS.json')}));
