import test from 'node:test';
import strict from 'node:assert/strict';
import fs from 'node:fs';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve,join} from 'node:path';
import {ANALYSIS,HERE,validatePartition,validateTerminal,terminalResource,checkLineage,safePath,evidence,hash,loadGate} from './gate.mjs';
import {resourceAccounting,QUALIFICATIONS} from './analyze-qualified.mjs';
import {interfaceResources} from './interface-resources.mjs';
import {scoreEvents,analyzeScores} from '../tether-robustness-shifts/repo-evaluation/experimental/analysis/scores.mjs';
import {extractDiagnostics,aggregateCalibration,aggregateNativeDiagnostics} from '../tether-robustness-shifts/repo-evaluation/experimental/analysis/diagnostics.mjs';
import {FAMILIES} from '../tether-robustness-shifts/repo-evaluation/experimental/analysis/statistics.mjs';
import {serialize,parse} from '../tether-robustness-shifts/repo-evaluation/experimental/analysis/vendor/raw-stream.mjs';
const counts={original:1,resume:1};
function partitionFixture(){return {expected:[{id:'a'},{id:'b'}],partition:{completedIds:['a'],remainingIds:['b'],partialIds:['b'],notStartedIds:[]},union:{acceptedOriginal:1,acceptedResume:1,entries:[{taskId:'a',origin:'original'},{taskId:'b',origin:'resume'}]}};}
for(const [name,alter]of [['duplicate',f=>f.union.entries.push(f.union.entries[0])],['unknown',f=>f.union.entries[1].taskId='x'],['missing',f=>f.union.entries.pop()],['substitution',f=>f.union.entries[0].origin='resume'],['overlap',f=>f.partition.completedIds.push('b')],['unknown origin',f=>f.union.entries[1].origin='other']])test('partition rejects '+name,()=>{const f=partitionFixture();alter(f);strict.throws(()=>validatePartition(f.expected,f.partition,f.union,counts));});
test('exact partition succeeds',()=>{const f=partitionFixture();validatePartition(f.expected,f.partition,f.union,counts);});
function terminalFixture(){const complete={at:'2026-10-03T09:00:00Z',status:'COMPLETE_NEEDS_INDEPENDENT_ANALYSIS',error:null,completed:2,total:2};return {complete,terminal:{type:'terminal',...complete},exit:{status:'VERIFIED_SUCCESSFUL_PROCESS_EXIT',exitCode:0,signal:null,observationSource:'execution-tool-terminal-response',sessionId:123,observedAt:'2026-10-03T09:00:01Z'},failed:false,uncertain:false,expectedTotal:2};}
test('genuine terminal and process exit required',()=>validateTerminal(terminalFixture()));
for(const [name,alter]of [['failure',f=>f.failed=true],['uncertain',f=>f.uncertain=true],['nonzero exit',f=>f.exit.exitCode=1],['missing exit',f=>f.exit.status='UNKNOWN'],['terminal mismatch',f=>f.terminal.completed=1],['missing COMPLETE',f=>f.complete.status='RUNNING']])test('terminal rejects '+name,()=>{const f=terminalFixture();alter(f);strict.throws(()=>validateTerminal(f));});
const usage={userCPUTime:12,systemCPUTime:3};
const receipt={taskId:'b',raw:{bytes:7}};
const ipc={pid:5,message:{ok:true,result:receipt,terminalResourceUsage:usage}};
const exit={pid:5,code:0,signal:null,ipcReceived:true,resourceSnapshotFresh:true,checkError:null};
test('historical terminal unavailable remains null through frozen JSON serializer',()=>{strict.equal(terminalResource('original',{},null,null,receipt),null);strict.equal(parse(serialize({terminalResourceUsage:terminalResource('original',{},null,null,receipt)})).terminalResourceUsage,null);});
test('historical invented CPU rejected',()=>strict.throws(()=>terminalResource('original',{terminalResourceUsage:usage},null,null,receipt)));
test('genuine resumed terminal IPC retained',()=>strict.deepEqual(terminalResource('resume',{terminalResourceUsage:usage},ipc,exit,receipt),usage));
for(const [name,alter]of [['missing terminal',f=>delete f.ipc.message.terminalResourceUsage],['receipt substitution',f=>f.ipc.message.result.taskId='x'],['failed child',f=>f.exit.code=1],['stale exit',f=>f.exit.resourceSnapshotFresh=false],['wrong PID',f=>f.exit.pid=9],['altered union resource',f=>f.entry.terminalResourceUsage.userCPUTime=20]])test('resumed resource rejects '+name,()=>{const f={ipc:structuredClone(ipc),exit:structuredClone(exit),entry:{terminalResourceUsage:structuredClone(usage)},receipt:structuredClone(receipt)};alter(f);strict.throws(()=>terminalResource('resume',f.entry,f.ipc,f.exit,f.receipt));});
function memoryFixture(){return {task:{cluster:0,condition:'c',arm:'mind-full',seat:0,bout:0},lock:{trainingSnapshotObjectHashes:['snapshot']},map:new Map()};}
test('cross-origin bout linkage succeeds and is session-specific',()=>{const f=memoryFixture();checkLineage(f.task,{inputMemorySha256:'snapshot'},{outputMemorySha256:'original-out'},f.lock,f.map);checkLineage({...f.task,bout:1},{inputMemorySha256:'original-out'},{outputMemorySha256:'resumed-out'},f.lock,f.map);strict.throws(()=>checkLineage({...f.task,bout:1,seat:1},{inputMemorySha256:'original-out'},{outputMemorySha256:'x'},f.lock,f.map));});
test('memory predecessor, initial snapshot and frozen invariants cannot be weakened',()=>{const f=memoryFixture();strict.throws(()=>checkLineage({...f.task,bout:1},{inputMemorySha256:'x'},{outputMemorySha256:'y'},f.lock,f.map));strict.throws(()=>checkLineage(f.task,{inputMemorySha256:'wrong'},{outputMemorySha256:'x'},f.lock,f.map));strict.throws(()=>checkLineage({...f.task,arm:'mind-learning-frozen'},{inputMemorySha256:'snapshot'},{outputMemorySha256:'x',acceptedInitialMemorySha256:'y',freezeLearningInvariant:{unchanged:true}},f.lock,f.map));});
test('artifact path escapes, source substitution and symlinks fail',()=>{const dir=mkdtempSync(join(tmpdir(),'qualified-path-'));try{fs.mkdirSync(join(dir,'raw'));const p=join(dir,'raw/a.gz');fs.writeFileSync(p,'synthetic');strict.equal(safePath(dir,p,'raw/a.gz'),p);strict.throws(()=>safePath(dir,p,'raw/b.gz'));strict.throws(()=>safePath(dir,join(dir,'../other'),'../other'));fs.symlinkSync(p,join(dir,'raw/link'));strict.throws(()=>safePath(dir,join(dir,'raw/link'),'raw/link'));}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('tampered evidence hash fails',()=>{const dir=mkdtempSync(join(tmpdir(),'qualified-hash-'));try{const path=join(dir,'mock.json');fs.writeFileSync(path,'{}');const ref={path,sha256:hash(Buffer.from('{}'))};strict.deepEqual(evidence(ref,'mock'),{});fs.writeFileSync(path,'{"changed":true}');strict.throws(()=>evidence(ref,'mock'));}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('absent explicit root release blocks before attempt access',()=>{const dir=mkdtempSync(join(tmpdir(),'qualified-release-'));try{const path=join(dir,'release.json');fs.writeFileSync(path,'{}');strict.throws(()=>loadGate(path),/root analysis release required/);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('frozen interface resource expression byte-identical',()=>{const original=fs.readFileSync(resolve(ANALYSIS,'analyze.mjs'),'utf8');const begin=original.indexOf('Object.fromEntries(design.arms.map(a=>{const rows=diagnostics'),end=original.indexOf(';assert(Math.abs',begin),expression=original.slice(begin,end-1);strict.ok(fs.readFileSync(resolve(HERE,'interface-resources.mjs'),'utf8').includes('return '+expression+';'));});
test('resource separation has no fake combined total or partial CPU',()=>{const diagnostics=['original','resume'].map(origin=>({recovery:{origin,rawBytes:7},resources:{processLifetimeCpu:{user:2,system:1},terminalResourceUsage:origin==='original'?null:usage}}));const gate={complete:{resources:{rawBytes:19},accounting:'synthetic snapshot scope'},recovery:{capacityLogicalCpus:9,capacityStart:'start',capacityDeadline:'end'},partials:[{bytes:5}]};const r=parse(serialize(resourceAccounting(diagnostics,gate)));strict.equal(r.original.terminalChildrenCpuSum,null);strict.equal(r.original.parentCpu,null);strict.equal(r.original.partialWorkersCpu,null);strict.equal(r.combinedFullPhaseCpu,null);strict.equal(r.resume.terminalChildrenCpuSum.count,1);strict.equal(r.acceptedRawBytes,14);strict.equal(r.originalPartialRawBytes,5);strict.equal(r.cumulativePhysicalAttemptRawBytes,19);strict.equal(r.capacityReservation.measuredCpu,false);strict.ok(r.qualifications.length>=9);});

// Synthetic fixture functions copied from frozen tests, never evaluation outcomes.
const checkNames=['actual-motor-transform','actual-command-commit','commit-timestamp','exact-sensor-delay-ticks','receipt-clock-roundoff-only','actual-report-present','workspace-focus','delivered-content','evidence-age-text','native-novelty','native-prediction','native-completion','pre-motor-report-command','pre-motor-diagnostic-command'];
function fixture(){const task={id:'synthetic',arm:'mind-fixed-metacog',seat:0,bout:0,cluster:0};const p={key:'situation',tactic:'lead',time:0,predictedFailure:.25};const out={...p,reward:1,actualFailure:0};const p2={...p,time:.0333333333333};const counts=Object.fromEntries(checkNames.map(name=>[name,{checked:2,mismatched:0,notApplicable:0,skippedMissingReport:0}]));const d=i=>({type:'decision',receiptTick:18+i*4,decisionIndex:i,definitions:[],focalInterfaceMs:2,visibility:[{opponent:true,opponentSpear:false,ownSpear:true},{}],preMotorCommand:{aimX:1,aimY:0},inputs:[{aimX:1,aimY:0},{}],faithfulness:{checks:checkNames.map(name=>({name,status:'pass'})),mismatches:[]},native:{serial:i,focus:'Hunt',situation:'situation',issuedTactic:'lead',habit:{tactic:'lead'},branchCompletion:[],tier:2,issuedLearningTier:2,automatic:true,novelty:{valid:true,familiar:!!i,family:'native-family',cell:'native-cell'},noveltyRequested:!i,noveltyForced:!i,monitorForced:false,handoffBlocked:false,planStatus:'completed',completedBranches:1,budget:{spent:192},fixedTeacher:{every:1,phase:0,due:true,opportunity:true,attempted:true,completed:true,issuedTeachingAction:true}},coordination:null});const rows=[{type:'task-start',initialLearningSupport:{}},{type:'native-pending-issue',id:'a',value:p,support:{situationPriorN:0,tacticPriorN:0,situationColdStart:true}},d(0),{type:'native-outcome',id:'a',value:out},{type:'native-pending-issue',id:'b',value:p2,support:{situationPriorN:1,tacticPriorN:1,situationColdStart:false}},d(1),{type:'calibration',row:{...out,origin:'native-pending',primaryCalibration:true,censored:false}},{type:'calibration',row:{...p2,origin:'native-pending',primaryCalibration:true,censored:true}},{type:'task-complete',result:{faithfulness:{counts,mismatches:[]},resources:{decisionWallSumMs:4}}}];return {rows,task};}

function factorialScores(mindDefault=0,mindShift=0){const arms=['mind-full','mind-no-novelty','mind-fixed-metacog','mind-learning-frozen','mind-broadcast-cut','conventional','conventional-useful-2x','conventional-useful-4x'];const rows=[];for(const arm of arms)for(const condition of ['default',...Object.values(FAMILIES).flat()])for(let cluster=0;cluster<12;cluster++)for(let seat=0;seat<2;seat++)for(let bout=0;bout<2;bout++){const net=arm==='mind-full'?(condition==='default'?mindDefault:mindShift):0;const task={id:`evaluation-c${cluster}-${condition}-${arm}-s${seat}-b${bout}`,arm,condition,cluster,seat,bout};rows.push({task,taskId:task.id,net,own:Math.max(net,0),opponent:Math.max(-net,0),windows:Array(5).fill({net:net/5}),draw:net===0,noScore:net===0,winPoints:net>0?1:net<0?0:.5,scoreShare:(Math.max(net,0)+.5)/(Math.abs(net)+1)});}return {rows,arms};}

test('recovery metadata and null historical resource cannot change frozen scientific outputs',()=>{
 const f=fixture();f.task.condition='default';const before=extractDiagnostics(f.rows,f.task,.8),after=extractDiagnostics(structuredClone(f.rows),structuredClone(f.task),.8);
 after.recovery={origin:'original',qualification:QUALIFICATIONS};after.resources.terminalResourceUsage=null;after.resources.processLifetimeCpu={user:2,system:1};
 strict.deepEqual(aggregateCalibration([before],Array(12).fill(.8)),aggregateCalibration([after],Array(12).fill(.8)));
 strict.deepEqual(aggregateNativeDiagnostics([before]),aggregateNativeDiagnostics([after]));
 const events=[{type:'event',tick:7200,event:{type:'HIT',attacker:'P1',phase:'OUTBOUND'}},{result:{score:[1,0]}}];const annotated=structuredClone(events);annotated.at(-1).result.resources={terminalResourceUsage:null,origin:'original'};
 strict.deepEqual(scoreEvents(events,{id:'synthetic',seat:0}),scoreEvents(annotated,{id:'synthetic',seat:0}));
 const {rows,arms}=factorialScores(2,1),a=analyzeScores(rows,arms);const changed=structuredClone(rows);changed.forEach(r=>{r.recovery={origin:'original'};r.resources={terminalResourceUsage:null};});strict.deepEqual(analyzeScores(changed,arms),a);
});
